apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vero026/restaurant-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017
            - name: MONGO_DB
              value: restaurant_db
            - name: SECRET_KEY
              value: mysecret123
            - name: ALLOWED_ORIGINS
              value: http://localhost:8080,http://127.0.0.1:8080