apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: restaurant-project
  namespace: argocd
spec:
  description: Project for Restaurant DevOps Application

  sourceRepos:
    - '*'

  destinations:
    - namespace: restaurant-dev
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'